// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParkApi.Models;

namespace NationalParkApi.Migrations
{
    [DbContext(typeof(NationalParkApiContext))]
    [Migration("20201030182632_SeedData2")]
    partial class SeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParkApi.Models.Reserve", b =>
                {
                    b.Property<int>("ReserveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ReserveName")
                        .IsRequired();

                    b.HasKey("ReserveId");

                    b.ToTable("Reserves");

                    b.HasData(
                        new
                        {
                            ReserveId = 1,
                            ReserveName = "North Cascades National Park"
                        },
                        new
                        {
                            ReserveId = 2,
                            ReserveName = "Mt. Hood NationalForest"
                        },
                        new
                        {
                            ReserveId = 3,
                            ReserveName = "Zion National Park"
                        },
                        new
                        {
                            ReserveId = 4,
                            ReserveName = "Yosemite National Park"
                        },
                        new
                        {
                            ReserveId = 5,
                            ReserveName = "Yellowstone National Park"
                        });
                });

            modelBuilder.Entity("NationalParkApi.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StateName")
                        .IsRequired();

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "Washington"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Oregon"
                        },
                        new
                        {
                            StateId = 3,
                            StateName = "Utah"
                        },
                        new
                        {
                            StateId = 4,
                            StateName = "California"
                        },
                        new
                        {
                            StateId = 5,
                            StateName = "Montana"
                        });
                });

            modelBuilder.Entity("NationalParkApi.Models.StateReserve", b =>
                {
                    b.Property<int>("StateReserveId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReserveId");

                    b.Property<int>("StateId");

                    b.HasKey("StateReserveId");

                    b.HasIndex("ReserveId");

                    b.HasIndex("StateId");

                    b.ToTable("StateReserves");

                    b.HasData(
                        new
                        {
                            StateReserveId = 1,
                            ReserveId = 1,
                            StateId = 1
                        },
                        new
                        {
                            StateReserveId = 2,
                            ReserveId = 2,
                            StateId = 2
                        },
                        new
                        {
                            StateReserveId = 3,
                            ReserveId = 3,
                            StateId = 3
                        },
                        new
                        {
                            StateReserveId = 4,
                            ReserveId = 4,
                            StateId = 4
                        },
                        new
                        {
                            StateReserveId = 5,
                            ReserveId = 5,
                            StateId = 5
                        });
                });

            modelBuilder.Entity("NationalParkApi.Models.StateReserve", b =>
                {
                    b.HasOne("NationalParkApi.Models.Reserve", "Reserve")
                        .WithMany("States")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NationalParkApi.Models.State", "State")
                        .WithMany("States")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
