// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParkApi.Models;

namespace NationalParkApi.Migrations
{
    [DbContext(typeof(NationalParkApiContext))]
    [Migration("20201030175314_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParkApi.Models.Reserve", b =>
                {
                    b.Property<int>("ReserveId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ReserveName")
                        .IsRequired();

                    b.HasKey("ReserveId");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("NationalParkApi.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StateName")
                        .IsRequired();

                    b.HasKey("StateId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("NationalParkApi.Models.StateReserve", b =>
                {
                    b.Property<int>("StateReserveId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReserveId");

                    b.Property<int>("StateId");

                    b.HasKey("StateReserveId");

                    b.HasIndex("ReserveId");

                    b.HasIndex("StateId");

                    b.ToTable("StateReserves");
                });

            modelBuilder.Entity("NationalParkApi.Models.StateReserve", b =>
                {
                    b.HasOne("NationalParkApi.Models.Reserve", "Reserve")
                        .WithMany("States")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NationalParkApi.Models.State", "State")
                        .WithMany("States")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
